### ISSUE TITLE
Unexpected EOF While Parsing

### ISSUE THREAD

**Issue by hamzaabdullah90** [toxic-ig/Trity#1]
------------------------------------------------------
**# I think you forgot to sanitize the input!**
------------------------------------------------------
```
$ python install.py 

  ------------------
< Trity Installer!! >
  ------------------
         \   ^__^
          \  (oo)\_______
             (__)\       )\/
                 ||-----||
                 ||     ||

Operating Systems Available: 

--------------------------
(1) Kali Linux / Ubuntu / Raspbian
--------------------------

[>] Select Operating System: Kali Linux
Traceback (most recent call last):
  File "install.py", line 25, in <module>
    option = input("\033[0m[>] Select Operating System: \033[0m")
  File "<string>", line 1
    Kali Linux
             ^
SyntaxError: unexpected EOF while parsing
```

**Comment by toxic-ig** [comment]
Fixed, you need to type in 1 for it to install

**Comment by hamzaabdullah90** [comment]
I know that, however, It would be more appreciated if you can show a nice instructive message after someone made the wrong choice or a typo instead of making him speculate on it!
