### ISSUE TITLE
Cant start trity.

### ISSUE THREAD

**Issue by awgal** [toxic-ig/Trity#14]
Hi,
just some information on my setup. I am running the latest Kali Linux, on a Virtual Box.

After following all the instructions regarding the installation, with a successful installation. I type trity and I just get many errors.

> Traceback (most recent call last):
  File "/opt/trity/trity.py", line 13, in <module>
    from info import *
  File "/opt/trity/info.py", line 19, in <module>
    ipaddr = urlopen('http://ip.42.pl/raw').read()
  File "/usr/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 429, in open
    response = self._open(req, data)
  File "/usr/lib/python2.7/urllib2.py", line 447, in _open
    '_open', req)
  File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 1228, in http_open
    return self.do_open(httplib.HTTPConnection, req)
  File "/usr/lib/python2.7/urllib2.py", line 1201, in do_open
    r = h.getresponse(buffering=True)
  File "/usr/lib/python2.7/httplib.py", line 1121, in getresponse
    response.begin()
  File "/usr/lib/python2.7/httplib.py", line 438, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python2.7/httplib.py", line 394, in _read_status
    line = self.fp.readline(_MAXLINE + 1)
  File "/usr/lib/python2.7/socket.py", line 480, in readline
    data = self._sock.recv(self._rbufsize)
socket.error: [Errno 104] Connection reset by peer

any solutions on how to fix this?

**Comment by eudomoniacc** [comment]
pip install google

cd /opt/trity
leafpad searchs.py
change "from google import search" to "from googlesearch import search"

Done

**Comment by toxic-ig** [comment]
Fixed.

**Comment by mayhemrrr** [comment]
Didn't work or me
