### ISSUE TITLE
error at end of install

### ISSUE THREAD

**Issue by ph3n0m79** [toxic-ig/Trity#19]
Command "/usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-zmbISd/readline/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-EDrjN8-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-zmbISd/readline/

Can anyone give me a hint as to what might be causing this problem.  I'm running Kali on a Raspberry Pi3 

If I try to run trity I get the below:
Traceback (most recent call last):
  File "/opt/trity/trity.py", line 15, in <module>
    from twitter import *
  File "/opt/trity/twitter.py", line 3, in <module>
    from bs4 import BeautifulSoup as So
  File "/usr/lib/python2.7/dist-packages/bs4/__init__.py", line 30, in <module>
    from .builder import builder_registry, ParserRejectedMarkup
  File "/usr/lib/python2.7/dist-packages/bs4/builder/__init__.py", line 314, in <module>
    from . import _html5lib
  File "/usr/lib/python2.7/dist-packages/bs4/builder/_html5lib.py", line 70, in <module>
    class TreeBuilderForHtml5lib(html5lib.treebuilders._base.TreeBuilder):
AttributeError: 'module' object has no attribute '_base'

I'm a bit lost!

**Comment by toxic-ig** [comment]
Fixed. Try to run it again. Reinstall it and install Trity again.
