### ISSUE TITLE
Traceback (most recent call last)

### ISSUE THREAD

**Issue by Chintu91** [toxic-ig/Trity#2]
When i get open Trity  i show this message  
root@kali:~/Trity# trity
Traceback (most recent call last):
  File "/opt/trity/trity.py", line 29, in <module>
    from search import *
  File "/opt/trity/search.py", line 1, in <module>
    from google import search
ImportError: No module named google

**Comment by toxic-ig** [comment]
apt-get update (or apt-get install update I forget)
pip uninstall google
pip install google

**Comment by bluecryptonite** [comment]
root@kali:~/Desktop/Trity# pip install netifaces
Requirement already satisfied: netifaces in /usr/local/lib/python3.5/dist-packages
root@kali:~/Desktop/Trity# trity
Traceback (most recent call last):
  File "/opt/trity/trity.py", line 9, in <module>
    from smtp import *
  File "/opt/trity/smtp.py", line 2, in <module>
    import platform, netifaces
ImportError: No module named netifaces
root@kali:~/Desktop/Trity# trity
Traceback (most recent call last):
  File "/opt/trity/trity.py", line 9, in <module>
    from smtp import *
  File "/opt/trity/smtp.py", line 2, in <module>
    import platform, netifaces
ImportError: No module named netifaces
root@kali:~/Desktop/Trity#

**Comment by bluecryptonite** [comment]
root@kali:~/Desktop/Trity# pip install netifaces
Requirement already satisfied: netifaces in /usr/local/lib/python3.5/dist-packages

**Comment by bluecryptonite** [comment]
root@kali:~/Desktop/Trity# trity
Traceback (most recent call last):
  File "/opt/trity/trity.py", line 9, in <module>
    from smtp import *
  File "/opt/trity/smtp.py", line 2, in <module>
    import platform, netifaces
ImportError: No module named netifaces

**Comment by toxic-ig** [comment]
Run install.py. Fixed netifaces as well.
