### ISSUE TITLE
xss traceback

### ISSUE THREAD

**Issue by masterkill3** [toxic-ig/Trity#21]
Traceback (most recent call last):
  File "/opt/trity/trity.py", line 326, in <module>
    tritymain()
  File "/opt/trity/trity.py", line 219, in tritymain
    xss()
  File "/opt/trity/xss.py", line 36, in xss
    r = requests.get(xss_url)
  File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 69, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 50, in request
    response = session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 451, in request
    prep = self.prepare_request(req)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 382, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "/usr/local/lib/python2.7/dist-packages/requests/models.py", line 304, in prepare
    self.prepare_url(url, params)
  File "/usr/local/lib/python2.7/dist-packages/requests/models.py", line 362, in prepare_url
    to_native_string(url, 'utf8')))
requests.exceptions.MissingSchema: Invalid URL '\x1b[93m\x1b[4mFull URL> \x1b[0m<body onload=alert("XSS")>': No schema supplied. Perhaps you meant http://Full URL> <body onload=alert("XSS")>?

**Comment by toxic-ig** [comment]
Fixed.
