### ISSUE TITLE
info option

### ISSUE THREAD

**Issue by masterkill3** [toxic-ig/Trity#22]
is my python problem?
Traceback (most recent call last):
  File "/opt/trity/trity.py", line 326, in <module>
    tritymain()
  File "/opt/trity/trity.py", line 325, in tritymain
    tritymain()
  File "/opt/trity/trity.py", line 169, in tritymain
    info()
  File "/opt/trity/info.py", line 34, in info
    FILE = open("othr/CompNetInfo.txt","w")
IOError: [Errno 2] No such file or directory: 'othr/CompNetInfo.txt'

**Comment by toxic-ig** [comment]
What version of python do you have?

**Comment by toxic-ig** [comment]
Try it now. I have fixed it.
