### ISSUE TITLE
Connection reset by peer

### ISSUE THREAD

**Issue by Soomrojb** [toxic-ig/Trity#26]
Running in Raspbian (rpi3):

Traceback (most recent call last):
  File "/opt/trity/trity.py", line 148, in <module>
    r = requests.get('http://pastebin.com/raw/vYcBSV4w')
  File "/usr/lib/python2.7/dist-packages/requests/api.py", line 60, in get
    return request('get', url, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/api.py", line 49, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 457, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 569, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/adapters.py", line 407, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', error(104, 'Connection reset by peer'))

**Comment by red-green** [comment]
looks like the script can't run without internet as it grabs a version file from pastebin. seems like bad coding practice to me...

**Comment by toxic-ig** [comment]
How should I edit it to make it a better coding practice? @red-green

**Comment by toxic-ig** [comment]
Updated code. Try again @Soomrojb

**Comment by Cloogo** [comment]
I use https instead of http
r = requests.get('https://pastebin.com/raw/vYcBSV4w')
and it works.

**Comment by red-green** [comment]
Put it in a try statement
