### ISSUE TITLE
Traceback (most recent call last)

### ISSUE THREAD

**Issue by huntsman1** [toxic-ig/Trity#28]
Traceback (most recent call last):
  File "/opt/trity/trity.py", line 318, in <module>
    tritymain()
  File "/opt/trity/trity.py", line 215, in tritymain
    sms()
  File "/opt/trity/sms.py", line 40, in sms
    o.login(gmail, password)
  File "/usr/lib/python2.7/smtplib.py", line 623, in login
    raise SMTPAuthenticationError(code, resp)
smtplib.SMTPAuthenticationError: (535, '5.7.8 Username and Password not accepted. Learn more at\n5.7.8  https://support.google.com/mail/?p=BadCredentials k71sm2533769pfg.52 - gsmtp')

**Comment by toxic-ig** [comment]
Make sure to have "less secure apps" turned on in gmail settings

**Comment by VolkenF15** [comment]
Traceback (most recent call last):
  File "./brut3k1t", line 98, in <module>
    main()
  File "./brut3k1t", line 86, in main
    w.execute()
  File "/root/brut3k1t/core/web.py", line 42, in execute
    if self.usercheck(self.username, self.service) == 1:
  File "/root/brut3k1t/core/web.py", line 51, in usercheck
    driver = webdriver.Firefox()
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/firefox/webdriver.py", line 152, in __init__
    self.service.start()
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/common/service.py", line 76, in start
    stdin=PIPE)
  File "/usr/lib/python2.7/subprocess.py", line 394, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1047, in _execute_child
    raise child_exception
OSError: [Errno 8] Exec format error

**Comment by VolkenF15** [comment]
./brut3k1t -s instagram -u DFRt -w '/root/brut3k1t/wordlist.txt' -d 5


  _                _   _____ _    _ _
 | |__  _ __ _   _| |_|___ /| | _/ | |_
 | '_ \| '__| | | | __| |_ \| |/ / | __|
 | |_) | |  | |_| | |_ ___) |   <| | |_
 |_.__/|_|   \__,_|\__|____/|_|\_\_|\__|
    Written by: @ex0dus-0x
 
[*] Username: DFRt
[*] Wordlist: /root/brut3k1t/wordlist.txt 
[*] Service: instagram 
[*] Checking if username exists...
Traceback (most recent call last):
  File "./brut3k1t", line 98, in <module>
    main()
  File "./brut3k1t", line 86, in main
    w.execute()
  File "/root/brut3k1t/core/web.py", line 42, in execute
    if self.usercheck(self.username, self.service) == 1:
  File "/root/brut3k1t/core/web.py", line 51, in usercheck
    driver = webdriver.Firefox()
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/firefox/webdriver.py", line 152, in __init__
    self.service.start()
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/common/service.py", line 76, in start
    stdin=PIPE)
  File "/usr/lib/python2.7/subprocess.py", line 394, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1047, in _execute_child
    raise child_exception
OSError: [Errno 8] Exec format error
