### ISSUE TITLE
error what?

### ISSUE THREAD

**Issue by kan11jia28** [toxic-ig/Trity#29]
Traceback (most recent call last):
  File "/opt/trity/trity.py", line 27, in <module>
    from searchs import *
  File "/opt/trity/searchs.py", line 1, in <module>
    from google import search
ImportError: cannot import name search

**Comment by toxic-ig** [comment]
Did you run install.py? @kan11jia28

**Comment by kan11jia28** [comment]
no,i run trity

**Comment by kan11jia28** [comment]
Traceback (most recent call last):
  File "/opt/trity/trity.py", line 151, in <module>
    r = requests.get('http://pastebin.com/raw/vYcBSV4w') 
  File "/usr/lib/python2.7/dist-packages/requests/api.py", line 70, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/api.py", line 56, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 488, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 609, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/adapters.py", line 473, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', error(104, 'Connection reset by peer'))

**Comment by toxic-ig** [comment]
Run install.py to install the tool and install the needed modules @kan11jia28

**Comment by kan11jia28** [comment]
Kali linux 2017.1 running error
All dependencies are installed
What does this mean?

**Comment by kan11jia28** [comment]
The problem is that all of my dependencies are installed successfully, that is, after the operation trity order error, install.py also installed a lot of times, in the end what the problem
| ----- Version: 3.4 ----- |
| ----- 1 tool - 35 choices ----- |

| ----- A Warm Welcome to Trity! ----- |
| ----- Awesome Pentesting tool! ----- |
| ----- Have Fun and Stay Legal! ----- |
Traceback (most recent call last):
  File "/opt/trity/trity.py", line 151, in <module>
    R = requests.get ('http://pastebin.com/raw/vYcBSV4w')
  File "/usr/lib/python2.7/dist-packages/requests/api.py", line 70, in get
    Return request ('get', url, params = params, ** kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/api.py", line 56, in request
    Return session.request (method = method, url = url, ** kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 488, in request
    Resp = self.send (prep, ** send_kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 609, in send
    R = adapter.send (request, ** kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/adapters.py", line 473, in send
    Raise ConnectionError (err, request = request)
Requests.exceptions.ConnectionError: ('Connection aborted.', Error (104, 'Connection reset by peer'))

**Comment by toxic-ig** [comment]
Updated code, re-clone, try again and report.

**Comment by kan11jia28** [comment]
Re-clone, update the source, and then install.py
Run trity
Or wrong
|----- Made by _t0x1c aka toxic -----|
|-----      Version: 3.4        -----|
|-----   1 tool - 35 choices    -----|

|----- A Warm Welcome to Trity! -----|
|----- Awesome Pentesting tool! -----|
|----- Have Fun and Stay Legal! -----|
Traceback (most recent call last):
  File "/opt/trity/trity.py", line 151, in <module>
    r = requests.get('http://pastebin.com/raw/vYcBSV4w') 
  File "/usr/lib/python2.7/dist-packages/requests/api.py", line 70, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/api.py", line 56, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 488, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 609, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/adapters.py", line 473, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', error(104, 'Connection reset by peer'))

What is the reason
Fast crashed

**Comment by kan11jia28** [comment]
Has just succeeded once, and later on the same as the original mistakes
Connection problem?

**Comment by toxic-ig** [comment]
Probably yes, let me update again. Try it again. @kan11jia28

**Comment by toxic-ig** [comment]
Alright, try again. @kan11jia28

**Comment by kan11jia28** [comment]
Still wrong
Re-clone and re-install.py

**Comment by kan11jia28** [comment]
Such a good procedure can not be used is really a pity
When will the problem of connection be repaired?

**Comment by arni9601** [comment]
I have the same problem, i need help
