### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by saikoekos** [toxic-ig/Trity#3]
Traceback (most recent call last):
  File "/opt/trity/trity.py", line 138, in <module>
    r = requests.get('http://pastebin.com/raw/vYcBSV4w') 
  File "/usr/lib/python2.7/dist-packages/requests/api.py", line 70, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/api.py", line 56, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 488, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 609, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/adapters.py", line 487, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='pastebin.com', port=80): Max retries exceeded with url: /raw/vYcBSV4w (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x7fca1d006cd0>: Failed to establish a new connection: [Errno 111] Connection refused',))

**Comment by toxic-ig** [comment]
You don't have internet man.
