### ISSUE TITLE
many errors

### ISSUE THREAD

**Issue by HoudaB** [toxic-ig/Trity#5]
Hi, I installed Trity but when I do an action like spoof email I have man errors like this :
Traceback (most recent calla last) : 
File "/opt/trity/trity.py", line 318, in <modue> tritymain()...................................

Do you know what's the problem originated?

**Comment by shannonliang312** [comment]
I install trity on my raspberry pi, and there is only 1 error.......so I modified the source code where the error happens, and it works now.
my error locates in trity.py, line 149

**Comment by toxic-ig** [comment]
I cannot help you because you have not given me enough info @HoudaB

**Comment by HoudaB** [comment]
Thank's for your help, I will try this.

**Comment by naffchwan** [comment]
i tried running anonymous module and i get the following error message

Enter the subject: test
Message: 
>nothing
Traceback (most recent call last):
  File "/opt/trity/trity.py", line 318, in <module>
    tritymain()
  File "/opt/trity/trity.py", line 221, in tritymain
    anon()
  File "/opt/trity/anon.py", line 27, in anon
    br.select_form(nr=0)
  File "/usr/local/lib/python2.7/dist-packages/mechanize/_mechanize.py", line 619, in select_form
    global_form = self._factory.global_form
  File "/usr/local/lib/python2.7/dist-packages/mechanize/_html.py", line 260, in global_form
    self.forms()
  File "/usr/local/lib/python2.7/dist-packages/mechanize/_html.py", line 267, in forms
    self._current_forms, self._current_global_form = self._get_forms()
  File "/usr/local/lib/python2.7/dist-packages/mechanize/_html.py", line 282, in _get_forms
    if self.root is None:
  File "/usr/local/lib/python2.7/dist-packages/mechanize/_html.py", line 247, in root
    response, verify=False))
  File "/usr/local/lib/python2.7/dist-packages/mechanize/_html.py", line 149, in content_parser
    namespaceHTMLElements=False)
TypeError: parse() got an unexpected keyword argument 'transport_encoding'

**Comment by toxic-ig** [comment]
Much to vague to fix anything
