### ISSUE TITLE
ImportError: No module named qrcode

### ISSUE THREAD

**Issue by mrseamonkey** [toxic-ig/Trity#7]
##trity
Traceback (most recent call last):
  File "/opt/trity/trity.py", line 26, in <module>
    from qr import *
  File "/opt/trity/qr.py", line 4, in <module>
    import qrcode
ImportError: No module named qrcode
I got this error after i tried to run trity --help me

**Comment by bluecryptonite** [comment]
Traceback (most recent call last):
  File "/opt/trity/trity.py", line 9, in <module>
    from smtp import *
  File "/opt/trity/smtp.py", line 2, in <module>
    import platform, netifaces
ImportError: No module named netifaces

**Comment by toxic-ig** [comment]
Run setup.py first and execute pip install qrcode.

**Comment by toxic-ig** [comment]
Fixed. Run install.py
